services:
  waha:
    restart: always
    image: devlikeapro/waha:latest
    ports:
      - '3009:3009/tcp'
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media

    environment:
      - WHATSAPP_API_PORT=3009
      - WHATSAPP_API_HOSTNAME=tests.devlike.pro
      - WHATSAPP_DEFAULT_ENGINE=NOWEB

      - WHATSAPP_API_KEY=123

      - WAHA_DASHBOARD_ENABLED=True
      - WAHA_DASHBOARD_USERNAME=waha
      - WAHA_DASHBOARD_PASSWORD=waha

      - WHATSAPP_SWAGGER_ENABLED=True
      - WHATSAPP_SWAGGER_USERNAME=swagger
      - WHATSAPP_SWAGGER_PASSWORD=swagger

      - WAHA_LOG_FORMAT=JSON
      - WAHA_LOG_LEVEL=info


      - WHATSAPP_RESTART_ALL_SESSIONS=True
      - WAHA_PRINT_QR=False
      - WHATSAPP_SWAGGER_CONFIG_ADVANCED=true

      - WHATSAPP_FILES_LIFETIME=0
      - WHATSAPP_FILES_FOLDER=/app/.media

volumes:
  waha_sessions: {}
  waha_media: {}
